name: Upload Docker Image

on:
  release:
    types: [ created ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      OWNER: clariteia
      IMAGE_NAME: minos-microservice

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Extract release version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV

      - name: Build Image
        run: docker build -t ghcr.io/$OWNER/$IMAGE_NAME:$RELEASE_VERSION --no-cache .

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish package
        run: docker push ghcr.io/$OWNER/$IMAGE_NAME:$RELEASE_VERSION

